Fixing permissions in CDs. Refs #3

diff --git a/.github/workflows/cd-master.yml b/.github/workflows/cd-master.yml
--- a/.github/workflows/cd-master.yml
+++ b/.github/workflows/cd-master.yml
@@ -57,12 +57,12 @@ jobs:
             echo ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
             # Ensure network exists
-            docker network inspect devops >/dev/null 2>&1 || docker network create devops
+            sudo docker network inspect devops >/dev/null 2>&1 || docker network create devops
 
-            docker pull ghcr.io/${{ env.REPOSITORY }}:latest
-            docker rm -f ${{ env.ARTIFACT }} || true
+            sudo docker pull ghcr.io/${{ env.REPOSITORY }}:latest
+            sudo docker rm -f ${{ env.ARTIFACT }} || true
 
-            docker run -d \
+            sudo docker run -d \
               --name ${{ env.ARTIFACT }} \
               --restart always \
               --memory 512m \
@@ -78,4 +78,4 @@ jobs:
             echo "⏳ waiting for container to be up"
             sleep 15
 
-            docker ps | grep ${{ env.ARTIFACT }} && echo "✅ Deploy successful" || echo "❌ Deploy failed"
+            sudo docker ps | grep ${{ env.ARTIFACT }} && echo "✅ Deploy successful" || echo "❌ Deploy failed"
