Fixing Render configuration and cd-staging.yml.

diff --git a/.github/workflows/cd-staging.yml b/.github/workflows/cd-staging.yml
--- a/.github/workflows/cd-staging.yml
+++ b/.github/workflows/cd-staging.yml
@@ -53,10 +53,6 @@ jobs:
             ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:latest
 
       - name: Deploy on Render
-        run:  |
-          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}"
-          && echo "Deployed on Render!" \
-          || echo "Failed to deploy on Render!"
-          
-          echo "Deployed on Render!"
+        run: |
+          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}" && echo "Deployed on Render!" || echo "Failed to deploy on Render!"
           docker image prune --filter "until=12h" -f
