Render configuration and cd-staging.yml added.

diff --git a/.github/workflows/cd-staging.yml b/.github/workflows/cd-staging.yml
--- a/.github/workflows/cd-staging.yml
+++ b/.github/workflows/cd-staging.yml
@@ -51,3 +51,12 @@ jobs:
           tags: |
             ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
             ${{ env.GHCR_URL }}/${{ env.REPOSITORY }}:latest
+
+      - name: Deploy on Render
+        run:  |
+          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_DEPLOY_HOOK_TOKEN }}"
+          && echo "Deployed on Render!" \
+          || echo "Failed to deploy on Render!"
+          
+          echo "Deployed on Render!"
+          docker image prune --filter "until=12h" -f
